### ISSUE TITLE
Having trouble with buidling

### ISSUE THREAD

**Issue by balistajnac** [fuwn/nitrous#17] opened 2021-08-17 15:14 UTC
I am having issues installing the build, at around 110 compiles the build fails, the first time it asked me to add an environmental variable such as "RUST_BACKTRACE=1" and then the second time "RUST_BACKTRACE=full" yet the build still fails. 

Just by reading this you could probably sense that I am fairly new to linux, I have only used it for 4 months and I won't know at least 75% of the stuff you guys do. So what can I do under these circumstances:

file:///home/anonymous/Pictures/Screenshot_2021-08-17_16_12_37.png

**Comment by fuwn** [comment] 2021-08-17 20:00
Could you include a the output the installation command emits?

**Comment by fuwn** [comment] 2021-08-21 00:07
Possible duplicate of #16

**Comment by fuwn** [comment] 2021-09-06 20:23
Closing this due to inactivity.

**Closed by fuwn** 2021-09-06 20:23 UTC
Labels: duplicate
